print("Welcome to Bandname Generator")
city = input("What's the name of your city you grew up in?\n")
print(city)
pet = input("What is the name of your pet?\n")
print(pet)
print("Your Bandname is " + city + " " + pet)
